volumes:
  postgres_data:
  zookeeper_data:
  kafka_data:

x-app: &app
  logging:
    driver: "json-file"
    options:
      max-file: "3"
      max-size: "10m"
  env_file:
    - ./.env
  restart: always

services:
  postgres:
    <<: *app
    image: postgres:14.0
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - ${POSTGRES_PORT}:5432

  fastapi:
    <<: *app
    container_name: fastapi
    build:
      context: ./
      dockerfile: ./src/Dockerfile
      target: ${API_CONTAINER_STAGE}
    ports:
      - ${API_PORT}:8000
    depends_on:
      - postgres

  nginx:
    <<: *app
    build:
      context: ./nginx
      dockerfile: ./Dockerfile
    ports:
      - ${NGINX_PORT}:80
    depends_on:
      - fastapi
